### ISSUE TITLE
[FR] add supported nim version, compiler options to readme

### ISSUE THREAD

**Issue by ITwrx** [can-lehmann/owlkettle#64] opened 2023-06-24 16:08 UTC
It would be nice if the nim version owlkettle is being tested with, as well as compiler options used, were documented in the readme. I just tried compiling with nim-1.6.12 and orc and i'm getting errors like:

```
/home/itwrx/.cache/nim/muhapp_d/@mviews@sroutine_list.nim.c:3049:17: error: ‘colontmpD_’ undeclared (first use in this function)
 3049 |                 colontmpD_ = (*((void**) (stateX60gensym3_)));
```
and:

```
/home/itwrx/.cache/nim/muhapp_d/@m..@s..@s..@s..@s..@s.nimble@spkgs@sowlkettle-@hhead@sowlkettle@swidgets.nim.c:26721:17: error: ‘colontmpD_’ undeclared (first use in this function)
26721 |                 colontmpD_ = (*((void**) (stateX60gensym1_)));
```
compiling with refc, boehm, markAndSweep, and go works.

thanks

**Comment by can-lehmann** [comment] 2023-06-24 22:40
This is a nim codegen issue, not a bug in owlkettle. It looks like it has been fixed in Nim devel though.

**Comment by ITwrx** [comment] 2023-06-24 22:49
Thanks, that's good to know, but what about the FR? I still think it would be nice to mention what version(s) of nim and compiler/GC options owlkettle is targeting, so people don't have to guess/assume. The specific issue i was having was just one possible example to illustrate the need for some clarity. If this info is not in readme idk if i'm supposed to ignore it as experimental, post as issue, ask question in discussions, or what.

thanks

**Closed** 2023-06-28 19:52 UTC
