### ISSUE TITLE
file_dialog segfault

### ISSUE THREAD

**Issue by luntik2012** [can-lehmann/owlkettle#17] opened 2022-06-09 20:15 UTC
```sh
$ ./file_dialog 

(file_dialog:82643): Gtk-WARNING **: 22:11:41.653: Theme parsing error: gtk-contained-dark.css:2871:228: Missing closing bracket for :not()

(file_dialog:82643): Gtk-WARNING **: 22:11:43.383: Invalid input string

(file_dialog:82643): Gtk-WARNING **: 22:11:43.383: Invalid input string

(file_dialog:82643): Gtk-WARNING **: 22:11:43.383: Invalid input string

(file_dialog:82643): Gtk-WARNING **: 22:11:43.383: Invalid input string
Traceback (most recent call last)
/tmp/owlkettle/examples/file_dialog.nim(59) file_dialog
/home/user/.nimble/pkgs/owlkettle-1.5.0/owlkettle.nim(72) brew
/home/user/.nimble/pkgs/owlkettle-1.5.0/owlkettle/widgets.nim(32) event_callback
/tmp/owlkettle/examples/file_dialog.nim(40) :anonymous
/home/user/.nimble/pkgs/owlkettle-1.5.0/owlkettle.nim(35) open
/home/user/.nimble/pkgs/owlkettle-1.5.0/owlkettle/widgetdef.nim(48) build
/home/user/.nimble/pkgs/owlkettle-1.5.0/owlkettle/widgets.nim(1369) build
SIGSEGV: Illegal storage access. (Attempt to read from nil?)
Segmentation fault (core dumped)
```

archlinux
Nim Compiler Version 1.6.6
to reproduce just click "Open" button

**Comment by can-lehmann** [comment] 2022-06-12 13:26
I am currently unable to reproduce this issue. Does it only occur when no item is selected? Which GTK version are you using?

**Comment by can-lehmann** [comment] 2022-07-13 20:39
Closing because of inactivity.

**Comment by can-lehmann** [comment] 2022-10-02 14:47
I finally was able to reproduce this when compiling with `-d:danger`. It should be fixed in https://github.com/can-lehmann/owlkettle/commit/d202473bb055201d34e7ae7245e83988f8410523.

**Comment by can-lehmann** [comment] 2022-10-02 15:24
Thank you for the detailed report. I think you still use the version without the fix, since it says "/home/user/.nimble/pkgs/owlkettle-2.0.0/owlkettle/widgetdef.nim (531, 6) Hint: 'gen_docs' is declared but not used [XDeclaredButNotUsed]" in the warning, but I renamed this function to "genDocs" since. Please try installing the latest version using `nimble install owlkettle@#head`.

I am also a bit confused why it does not render any text. The blue button should be labelled "Open".
![Screenshot](https://user-images.githubusercontent.com/85876381/193461950-a0123a38-7f17-414d-bacb-d0292f3b9d66.png)

**Comment by dlesnoff** [comment] 2022-11-01 15:12
@luntik2012 To get the version number of a specific library with nimble, you can do :
```raw
nimble list -i | grep owlkettle
```
Btw, with owlkettle 2.1.0, on Ubuntu 22.04.1,[DE: Gnome 42.4, WM: Mutter, WM Theme: Adwaita], this example file_dialog.nim works fine for me.
@luntik2012 Could you give us your WM & WM Theme ?

I'll try on my Arch desktop when at home.

**Comment by beef331** [comment] 2023-01-12 22:51
I tried it with endeavor OS which is Arch based and it worked fine here.  Seems to either been resolved in owlkettle or through updates to arch repositories.

**Comment by can-lehmann** [comment] 2023-01-12 23:08
@beef331 Thanks for testing this. Since multiple people were now unable to reproduce this issue, I will close it again for the time being.

**Closed by can-lehmann** 2023-01-12 23:08 UTC
Labels: help wanted

**Comment by dlesnoff** [comment] 2023-01-12 23:12
It also works on my Arch distribution. Sorry for the very late reply.

**Comment by can-lehmann** [comment] 2023-01-12 23:18
@dlesnoff No worries. I'm glad that it seems to be resolved.
